import type { Metadata } from 'next';

<<<<<<< HEAD
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import { ClerkProvider } from '@clerk/nextjs';
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { ModalProvider } from '@/providers/modal-provider';
=======
import { auth } from '@/auth';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { ModalProvider } from '@/providers/modal-provider';
import { SessionProvider } from 'next-auth/react';
>>>>>>> c2f603139cf147143f58034a06a1121f12db56d2
import { extractRouterConfig } from 'uploadthing/server';

import { cn } from '@/lib/utils';

import { ourFileRouter } from './api/uploadthing/core';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});
<<<<<<< HEAD
=======

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
>>>>>>> c2f603139cf147143f58034a06a1121f12db56d2

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html
        lang='en'
        suppressHydrationWarning
      >
        <body className={cn('min-h-screen bg-background font-nunito antialiased', inter.variable)}>
          <Toaster richColors />
          <ModalProvider />
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
